theme: minima
google_analytics: UA-137824421-1
url: "http://pyhoshen.org"
disqus:
  shortname: pyhoshen
twitter_username: pyhoshen
minima:
  social_links:
    twitter: pyhoshen
show_excerpts: true
excerpt_separator: "<!--more-->"
